# Generated by Django 5.2.1 on 2025-06-07 14:43

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="主键，BIGINT UNSIGNED AUTO_INCREMENT",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="记录创建时间，自动添加",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="记录更新时间，自动更新",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='人类可读的权限名，如 "查看订单"',
                        max_length=100,
                        unique=True,
                        verbose_name="权限名称",
                    ),
                ),
                (
                    "codename",
                    models.CharField(
                        help_text='程序中使用的权限标识，如 "view_order"',
                        max_length=100,
                        unique=True,
                        verbose_name="权限代码",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="权限描述"
                    ),
                ),
            ],
            options={
                "verbose_name": "权限",
                "verbose_name_plural": "权限",
                "db_table_comment": "自定义权限表",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="主键，BIGINT UNSIGNED AUTO_INCREMENT",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="记录创建时间，自动添加",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="记录更新时间，自动更新",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="角色名称"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="角色描述"
                    ),
                ),
            ],
            options={
                "verbose_name": "角色",
                "verbose_name_plural": "角色",
                "db_table_comment": "角色信息表",
            },
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="主键，BIGINT UNSIGNED AUTO_INCREMENT",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="记录创建时间，自动添加",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="记录更新时间，自动更新",
                        verbose_name="更新时间",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="菜单名称")),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        help_text="前端路由或链接",
                        max_length=255,
                        null=True,
                        verbose_name="菜单URL",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="例如 Element Plus 图标类名",
                        max_length=100,
                        null=True,
                        verbose_name="菜单图标",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="数字越小越靠前", verbose_name="显示顺序"
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True,
                        help_text="控制菜单是否在界面上显示",
                        verbose_name="是否可见",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="此菜单的父级菜单",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="users.menu",
                        verbose_name="父级菜单",
                    ),
                ),
            ],
            options={
                "verbose_name": "菜单",
                "verbose_name_plural": "菜单",
                "db_table_comment": "系统菜单配置表",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="电子邮箱"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="用于登录和接收通知",
                        max_length=20,
                        unique=True,
                        verbose_name="手机号码",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(1, "正常"), (2, "禁用"), (3, "删除")],
                        default=1,
                        help_text="例如：1-正常，2-禁用，3-删除",
                        verbose_name="用户状态",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=150, verbose_name="名字"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=150, verbose_name="姓氏"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="custom_user_groups",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "signing_company",
                    models.ForeignKey(
                        blank=True,
                        help_text="用户所属的签约公司（如果适用）",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organizations.signingcompany",
                        verbose_name="关联签约公司",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="custom_user_permissions",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
                "db_table_comment": "用户信息表",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="RoleMenuMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="主键，BIGINT UNSIGNED AUTO_INCREMENT",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="记录创建时间，自动添加",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="记录更新时间，自动更新",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        help_text="关联的菜单",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.menu",
                        verbose_name="菜单",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        help_text="关联的角色",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.role",
                        verbose_name="角色",
                    ),
                ),
            ],
            options={
                "verbose_name": "角色菜单映射",
                "verbose_name_plural": "角色菜单映射",
                "db_table_comment": "角色与菜单关系映射表",
                "unique_together": {("role", "menu")},
            },
        ),
        migrations.CreateModel(
            name="RolePermissionMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="主键，BIGINT UNSIGNED AUTO_INCREMENT",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="记录创建时间，自动添加",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="记录更新时间，自动更新",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        help_text="关联的自定义权限",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.permission",
                        verbose_name="权限",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        help_text="关联的角色",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.role",
                        verbose_name="角色",
                    ),
                ),
            ],
            options={
                "verbose_name": "角色权限映射",
                "verbose_name_plural": "角色权限映射",
                "db_table_comment": "角色与自定义权限关系映射表",
                "unique_together": {("role", "permission")},
            },
        ),
        migrations.CreateModel(
            name="UserRoleMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="主键，BIGINT UNSIGNED AUTO_INCREMENT",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="记录创建时间，自动添加",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="记录更新时间，自动更新",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        help_text="关联的角色",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.role",
                        verbose_name="角色",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="关联的用户",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户角色映射",
                "verbose_name_plural": "用户角色映射",
                "db_table_comment": "用户与角色关系映射表",
                "unique_together": {("user", "role")},
            },
        ),
    ]
