# Generated by Django 5.2.1 on 2025-06-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.AddField(
            model_name="user",
            name="contract_details",
            field=models.TextField(
                blank=True,
                help_text="存储与签约公司的合同相关信息",
                null=True,
                verbose_name="签约详情",
            ),
        ),
    ]
