# Generated by Django 5.2.1 on 2025-06-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_managers_user_contract_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(
                default=False,
                help_text="标记用户是否已通过实名认证流程",
                verbose_name="是否已实名认证",
            ),
        ),
    ]
