upstream django_server {
    server 127.0.0.1:8000; # Django Gunicorn/uWSGI 地址
}

upstream frontend_server {
    server 127.0.0.1:3000; # 前端开发服务器地址
}

server {
    listen 80;
    server_name localhost;

    location /api/ {
        proxy_pass http://django_server;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /static/ { # Django admin static files
        alias /app/staticfiles/; #  Updated path
    }

    location / {
        proxy_pass http://frontend_server;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
