# Generated by Django 5.2.1 on 2025-06-21 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permissions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="签约公司名称", max_length=255, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "签约公司",
                "verbose_name_plural": "签约公司",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DataPermissionCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="数据权限集合名称，例如：业务数据",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="数据权限集合编码，例如：business_data",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="数据权限集合描述", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "数据权限集合",
                "verbose_name_plural": "数据权限集合",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="集团名称", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        help_text="所属签约公司",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="permissions.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "集团",
                "verbose_name_plural": "集团",
                "ordering": ["company", "name"],
                "unique_together": {("company", "name")},
            },
        ),
        migrations.CreateModel(
            name="Enterprise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="企业名称", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        help_text="所属集团",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enterprises",
                        to="permissions.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "企业",
                "verbose_name_plural": "企业",
                "ordering": ["group", "name"],
                "unique_together": {("group", "name")},
            },
        ),
        migrations.CreateModel(
            name="UserCompanyAdminPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        help_text="管理的签约公司",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_users",
                        to="permissions.company",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="用户",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_admin_permission",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "签约公司管理员权限",
                "verbose_name_plural": "签约公司管理员权限",
                "unique_together": {("user", "company")},
            },
        ),
        migrations.CreateModel(
            name="UserEnterpriseDataPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "data_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="在该企业拥有的数据权限集合",
                        related_name="user_enterprise_assignments",
                        to="permissions.datapermissioncollection",
                    ),
                ),
                (
                    "enterprise",
                    models.ForeignKey(
                        help_text="关联的企业",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_permissions",
                        to="permissions.enterprise",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="用户",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enterprise_data_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "用户企业数据权限",
                "verbose_name_plural": "用户企业数据权限",
                "ordering": ["user", "enterprise"],
                "unique_together": {("user", "enterprise")},
            },
        ),
        migrations.CreateModel(
            name="UserGroupAdminPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        help_text="管理的集团",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_users",
                        to="permissions.group",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="用户",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_admin_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "集团管理员权限",
                "verbose_name_plural": "集团管理员权限",
                "unique_together": {("user", "group")},
            },
        ),
    ]
