# Generated by Django 5.2.1 on 2025-06-07 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DingtalkRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="主键，BIGINT UNSIGNED AUTO_INCREMENT",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="记录创建时间，自动添加",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="记录更新时间，自动更新",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "request_id",
                    models.CharField(
                        blank=True,
                        help_text="钉钉API请求的唯一ID",
                        max_length=100,
                        null=True,
                        verbose_name="请求ID",
                    ),
                ),
                (
                    "target_user",
                    models.CharField(
                        help_text="UserID列表, Chat ID等",
                        max_length=255,
                        verbose_name="目标用户/群组",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        default="text",
                        help_text="例如: text, markdown, action_card",
                        max_length=50,
                        verbose_name="消息类型",
                    ),
                ),
                (
                    "content",
                    models.JSONField(
                        help_text="结构化的消息体，符合钉钉API规范",
                        verbose_name="消息内容",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        default=0,
                        help_text="0-待发送, 1-成功, 2-失败",
                        verbose_name="发送状态",
                    ),
                ),
                (
                    "response_code",
                    models.CharField(
                        blank=True,
                        help_text="钉钉通常返回字符串形式的错误码",
                        max_length=50,
                        null=True,
                        verbose_name="服务商响应码",
                    ),
                ),
                (
                    "response_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="服务商响应消息"
                    ),
                ),
            ],
            options={
                "verbose_name": "钉钉记录",
                "verbose_name_plural": "钉钉记录",
                "db_table_comment": "钉钉消息发送记录表",
            },
        ),
        migrations.CreateModel(
            name="FeishuRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="主键，BIGINT UNSIGNED AUTO_INCREMENT",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="记录创建时间，自动添加",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="记录更新时间，自动更新",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "request_id",
                    models.CharField(
                        blank=True,
                        help_text="飞书API请求的唯一ID",
                        max_length=100,
                        null=True,
                        verbose_name="请求ID",
                    ),
                ),
                (
                    "target_user",
                    models.CharField(
                        help_text="User ID, Open ID, Chat ID等",
                        max_length=100,
                        verbose_name="目标用户/群组",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        default="text",
                        help_text="例如: text, post, image",
                        max_length=50,
                        verbose_name="消息类型",
                    ),
                ),
                (
                    "content",
                    models.JSONField(
                        help_text="结构化的消息体，符合飞书API规范",
                        verbose_name="消息内容",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        default=0,
                        help_text="0-待发送, 1-成功, 2-失败",
                        verbose_name="发送状态",
                    ),
                ),
                (
                    "response_code",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="服务商响应码"
                    ),
                ),
                (
                    "response_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="服务商响应消息"
                    ),
                ),
            ],
            options={
                "verbose_name": "飞书记录",
                "verbose_name_plural": "飞书记录",
                "db_table_comment": "飞书消息发送记录表",
            },
        ),
        migrations.CreateModel(
            name="SmsRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="主键，BIGINT UNSIGNED AUTO_INCREMENT",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="记录创建时间，自动添加",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="记录更新时间，自动更新",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="手机号"),
                ),
                ("content", models.TextField(verbose_name="短信内容")),
                (
                    "status",
                    models.SmallIntegerField(
                        default=0,
                        help_text="0-待发送, 1-成功, 2-失败",
                        verbose_name="发送状态",
                    ),
                ),
                (
                    "response_message",
                    models.TextField(blank=True, null=True, verbose_name="服务商响应"),
                ),
            ],
            options={
                "verbose_name": "短信记录",
                "verbose_name_plural": "短信记录",
                "db_table_comment": "短信发送记录表",
            },
        ),
        migrations.CreateModel(
            name="OssFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="主键，BIGINT UNSIGNED AUTO_INCREMENT",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="记录创建时间，自动添加",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="记录更新时间，自动更新",
                        verbose_name="更新时间",
                    ),
                ),
                ("file_name", models.CharField(max_length=255, verbose_name="文件名")),
                (
                    "file_url",
                    models.URLField(
                        max_length=1024, unique=True, verbose_name="文件URL"
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        help_text="例如：image/jpeg, application/pdf, text/csv",
                        max_length=100,
                        verbose_name="文件类型",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="关联到上传此文件的用户",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上传用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "OSS存储文件",
                "verbose_name_plural": "OSS存储文件",
                "db_table_comment": "对象存储文件记录表",
            },
        ),
        migrations.CreateModel(
            name="ImportExportTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="主键，BIGINT UNSIGNED AUTO_INCREMENT",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="记录创建时间，自动添加",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="记录更新时间，自动更新",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "task_name",
                    models.CharField(max_length=255, verbose_name="任务名称"),
                ),
                (
                    "task_type",
                    models.SmallIntegerField(
                        choices=[(1, "导入"), (2, "导出")],
                        help_text="1-导入, 2-导出",
                        verbose_name="任务类型",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[
                            (0, "待处理"),
                            (1, "处理中"),
                            (2, "成功"),
                            (3, "失败"),
                        ],
                        default=0,
                        help_text="0-待处理, 1-处理中, 2-成功, 3-失败",
                        verbose_name="任务状态",
                    ),
                ),
                (
                    "result_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="任务结果信息"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="关联到创建此任务的用户",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建用户",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        blank=True,
                        help_text="导入的文件或导出的结果文件",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.ossfile",
                        verbose_name="关联文件",
                    ),
                ),
            ],
            options={
                "verbose_name": "导入导出任务",
                "verbose_name_plural": "导入导出任务",
                "db_table_comment": "导入导出任务记录表",
            },
        ),
        migrations.CreateModel(
            name="SystemLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="主键，BIGINT UNSIGNED AUTO_INCREMENT",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="记录创建时间，自动添加",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="记录更新时间，自动更新",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("INFO", "信息"),
                            ("WARNING", "警告"),
                            ("ERROR", "错误"),
                            ("CRITICAL", "严重"),
                            ("DEBUG", "调试"),
                        ],
                        default="INFO",
                        max_length=20,
                        verbose_name="日志级别",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        help_text="例如：users, organizations, settlements",
                        max_length=100,
                        verbose_name="模块",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="例如：create_user, update_order_status",
                        max_length=255,
                        verbose_name="操作动作",
                    ),
                ),
                ("message", models.TextField(verbose_name="日志信息")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="执行操作的用户，可为空（如系统自动任务）",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "系统日志",
                "verbose_name_plural": "系统日志",
                "db_table_comment": "系统操作日志表",
            },
        ),
    ]
