# Generated by Django 5.2.1 on 2025-06-07 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="主键，BIGINT UNSIGNED AUTO_INCREMENT",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="记录创建时间，自动添加",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="记录更新时间，自动更新",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="规则名称"
                    ),
                ),
                (
                    "rule_type",
                    models.SmallIntegerField(
                        choices=[
                            (1, "转换提示"),
                            (2, "订单挂起"),
                            (3, "订单重发"),
                            (4, "渠道切换"),
                        ],
                        help_text="1-转换提示, 2-订单挂起, 3-订单重发, 4-渠道切换",
                        verbose_name="规则类型",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        help_text="例如重发间隔、次数；切换目标渠道；挂起原因等",
                        null=True,
                        verbose_name="规则配置",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="标记此规则是否生效",
                        verbose_name="是否激活",
                    ),
                ),
            ],
            options={
                "verbose_name": "订单处理规则",
                "verbose_name_plural": "订单处理规则",
                "db_table_comment": "支付订单处理规则配置表",
            },
        ),
        migrations.CreateModel(
            name="PaymentChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="主键，BIGINT UNSIGNED AUTO_INCREMENT",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="记录创建时间，自动添加",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="记录更新时间，自动更新",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="如：支付宝ISV, 微信支付, 银行卡快捷",
                        max_length=100,
                        unique=True,
                        verbose_name="支付渠道名称",
                    ),
                ),
                (
                    "channel_code",
                    models.CharField(
                        help_text="如：ALIPAY_ISV, WECHAT_PAY, BANK_QUICKPAY",
                        max_length=50,
                        unique=True,
                        verbose_name="渠道代码",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="标记此支付渠道是否可用",
                        verbose_name="是否激活",
                    ),
                ),
                (
                    "config_details",
                    models.JSONField(
                        blank=True,
                        help_text="存储API密钥、证书路径、回调地址等敏感信息（应加密存储或引用安全存储）",
                        null=True,
                        verbose_name="渠道配置详情",
                    ),
                ),
            ],
            options={
                "verbose_name": "支付渠道",
                "verbose_name_plural": "支付渠道",
                "db_table_comment": "支付渠道基础信息表",
            },
        ),
        migrations.CreateModel(
            name="ArrivalChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="主键，BIGINT UNSIGNED AUTO_INCREMENT",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="记录创建时间，自动添加",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="记录更新时间，自动更新",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="如：银行卡（借记卡）, 支付宝余额, 微信零钱",
                        max_length=100,
                        verbose_name="到账通道名称",
                    ),
                ),
                (
                    "channel_code",
                    models.CharField(
                        help_text="如：BANK_DEBIT, ALIPAY_BALANCE, WECHAT_WALLET. 应确保在所属支付渠道下唯一",
                        max_length=50,
                        verbose_name="到账通道代码",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="标记此到账通道是否可用",
                        verbose_name="是否激活",
                    ),
                ),
                (
                    "payment_channel",
                    models.ForeignKey(
                        help_text="此到账通道属于哪个主支付渠道",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="payment_channels.paymentchannel",
                        verbose_name="所属支付渠道",
                    ),
                ),
            ],
            options={
                "verbose_name": "到账通道",
                "verbose_name_plural": "到账通道",
                "db_table_comment": "支付渠道下的具体到账方式",
                "unique_together": {("payment_channel", "channel_code")},
            },
        ),
        migrations.CreateModel(
            name="PaymentSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="主键，BIGINT UNSIGNED AUTO_INCREMENT",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="记录创建时间，自动添加",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="记录更新时间，自动更新",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "subject_name",
                    models.CharField(
                        help_text="例如：XX公司支付宝账户",
                        max_length=200,
                        verbose_name="支付主体名称",
                    ),
                ),
                (
                    "account_name",
                    models.CharField(
                        help_text="银行开户名或第三方支付账户名",
                        max_length=200,
                        verbose_name="付款账户名称",
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        help_text="银行卡号或第三方支付账号（应加密存储）",
                        max_length=100,
                        verbose_name="付款账号",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="标记是否为所属签约公司在该渠道下的默认支付主体",
                        verbose_name="是否默认支付主体",
                    ),
                ),
                (
                    "configs",
                    models.JSONField(
                        help_text="特定于此主体的支付配置，如API子商户ID、公私钥、特定API地址等（应加密存储）",
                        verbose_name="支付配置",
                    ),
                ),
                (
                    "payment_channel",
                    models.ForeignKey(
                        help_text="此支付主体关联的支付渠道",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="payment_channels.paymentchannel",
                        verbose_name="支付渠道",
                    ),
                ),
                (
                    "signing_company",
                    models.ForeignKey(
                        help_text="此支付主体属于哪个签约公司",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.signingcompany",
                        verbose_name="所属签约公司",
                    ),
                ),
            ],
            options={
                "verbose_name": "支付主体",
                "verbose_name_plural": "支付主体",
                "db_table_comment": "签约公司在各支付渠道的支付主体账户信息",
                "unique_together": {
                    ("signing_company", "payment_channel", "account_number")
                },
            },
        ),
    ]
