# Generated by Django 5.2.1 on 2025-06-07 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="主键，BIGINT UNSIGNED AUTO_INCREMENT",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="记录创建时间，自动添加",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="记录更新时间，自动更新",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="集团名称"
                    ),
                ),
                (
                    "group_code",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="集团代码"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="集团描述"),
                ),
            ],
            options={
                "verbose_name": "集团",
                "verbose_name_plural": "集团",
                "db_table_comment": "集团信息表",
            },
        ),
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="主键，BIGINT UNSIGNED AUTO_INCREMENT",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="记录创建时间，自动添加",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="记录更新时间，自动更新",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="综合结算平台", max_length=100, verbose_name="平台名称"
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="例如：1.0.0", max_length=50, verbose_name="平台版本"
                    ),
                ),
            ],
            options={
                "verbose_name": "平台信息",
                "verbose_name_plural": "平台信息",
                "db_table_comment": "平台基本信息表（通常只有一条记录）",
            },
        ),
        migrations.CreateModel(
            name="SigningCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="主键，BIGINT UNSIGNED AUTO_INCREMENT",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="记录创建时间，自动添加",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="记录更新时间，自动更新",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="签约公司名称"
                    ),
                ),
                (
                    "company_code",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="公司代码"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="公司地址"
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="联系人"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="联系电话"
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(1, "正常"), (0, "禁用")],
                        default=1,
                        help_text="例如：1-正常，0-禁用",
                        verbose_name="状态",
                    ),
                ),
            ],
            options={
                "verbose_name": "签约公司",
                "verbose_name_plural": "签约公司",
                "db_table_comment": "签约公司信息表",
            },
        ),
        migrations.CreateModel(
            name="Merchant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="主键，BIGINT UNSIGNED AUTO_INCREMENT",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="记录创建时间，自动添加",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="记录更新时间，自动更新",
                        verbose_name="更新时间",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="商户名称")),
                (
                    "merchant_code",
                    models.CharField(
                        help_text="系统生成的唯一商户标识",
                        max_length=100,
                        unique=True,
                        verbose_name="商户代码",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[
                            (1, "待签约"),
                            (2, "已签约"),
                            (3, "已注销"),
                            (4, "审核中"),
                            (5, "审核拒绝"),
                        ],
                        default=1,
                        help_text="例如：1-待签约，2-已签约，3-已注销",
                        verbose_name="状态",
                    ),
                ),
                (
                    "contract_info",
                    models.TextField(
                        blank=True,
                        help_text="JSON格式存储合同编号、有效期等",
                        null=True,
                        verbose_name="签约信息",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        help_text="商户所属的集团（可选）",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organizations.group",
                        verbose_name="所属集团",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="关联到平台的管理员用户，用于操作此商户的业务",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="关联平台用户",
                    ),
                ),
                (
                    "signing_company",
                    models.ForeignKey(
                        help_text="该商户签约主体公司",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.signingcompany",
                        verbose_name="所属签约公司",
                    ),
                ),
            ],
            options={
                "verbose_name": "商户",
                "verbose_name_plural": "商户",
                "db_table_comment": "商户信息表",
                "unique_together": {("signing_company", "name")},
            },
        ),
    ]
