# Generated by Django 5.2.1 on 2025-06-07 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("payment_channels", "0001_initial"),
        ("settlements", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="主键，BIGINT UNSIGNED AUTO_INCREMENT",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="记录创建时间，自动添加",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="记录更新时间，自动更新",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="总余额，包括可用和冻结部分",
                        max_digits=18,
                        verbose_name="账户余额",
                    ),
                ),
                (
                    "available_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="可用于支付或提现的余额",
                        max_digits=18,
                        verbose_name="可用余额",
                    ),
                ),
                (
                    "frozen_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="因特定操作（如支付冻结、提现申请）被临时冻结的金额",
                        max_digits=18,
                        verbose_name="冻结余额",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(1, "正常"), (0, "冻结"), (2, "注销")],
                        default=1,
                        help_text="1-正常, 0-冻结, 2-注销",
                        verbose_name="账户状态",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        help_text="此账户属于哪个商户",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.merchant",
                        verbose_name="所属商户",
                    ),
                ),
                (
                    "payment_subject",
                    models.OneToOneField(
                        help_text="此账户关联到哪个支付主体（如特定银行卡或第三方支付账户）",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="payment_channels.paymentsubject",
                        verbose_name="关联支付主体",
                    ),
                ),
            ],
            options={
                "verbose_name": "商户账户",
                "verbose_name_plural": "商户账户",
                "db_table_comment": "商户在特定支付主体的资金账户表",
                "unique_together": {("merchant", "payment_subject")},
            },
        ),
        migrations.CreateModel(
            name="ElectronicReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="主键，BIGINT UNSIGNED AUTO_INCREMENT",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="记录创建时间，自动添加",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="记录更新时间，自动更新",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "receipt_file_url",
                    models.URLField(
                        blank=True,
                        help_text="指向存储在OSS等的文件链接",
                        max_length=1024,
                        null=True,
                        verbose_name="电子回单文件URL",
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="生成时间"
                    ),
                ),
                (
                    "payment_order",
                    models.OneToOneField(
                        help_text="此电子回单对应哪个支付订单",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="settlements.paymentorder",
                        verbose_name="关联支付订单",
                    ),
                ),
            ],
            options={
                "verbose_name": "电子回单",
                "verbose_name_plural": "电子回单",
                "db_table_comment": "支付订单的电子回单记录表",
            },
        ),
        migrations.CreateModel(
            name="ServiceFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="主键，BIGINT UNSIGNED AUTO_INCREMENT",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="记录创建时间，自动添加",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="记录更新时间，自动更新",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="服务费金额"
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[
                            (1, "已收取"),
                            (2, "已退回"),
                            (0, "待收取"),
                            (3, "收取失败"),
                        ],
                        default=0,
                        help_text="1-已收取, 2-已退回, 0-待收取, 3-收取失败",
                        verbose_name="状态",
                    ),
                ),
                (
                    "collected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="收取/退回时间"
                    ),
                ),
                (
                    "payment_order",
                    models.OneToOneField(
                        help_text="此服务费针对哪个支付订单收取",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="settlements.paymentorder",
                        verbose_name="关联支付订单",
                    ),
                ),
            ],
            options={
                "verbose_name": "服务费记录",
                "verbose_name_plural": "服务费记录",
                "db_table_comment": "支付订单的服务费记录表",
            },
        ),
        migrations.CreateModel(
            name="TransactionLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="主键，BIGINT UNSIGNED AUTO_INCREMENT",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="记录创建时间，自动添加",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="记录更新时间，自动更新",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "transaction_type",
                    models.SmallIntegerField(
                        choices=[
                            (1, "充值"),
                            (2, "提现"),
                            (3, "支付"),
                            (4, "退款"),
                            (5, "服务费收取"),
                            (6, "服务费退回"),
                            (7, "账户冻结"),
                            (8, "账户解冻"),
                            (9, "系统调账增"),
                            (10, "系统调账减"),
                        ],
                        help_text="说明资金变动的业务性质",
                        verbose_name="流水类型",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="正数表示增加，负数表示减少",
                        max_digits=18,
                        verbose_name="变动金额",
                    ),
                ),
                (
                    "balance_before",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="此流水发生前的账户总余额",
                        max_digits=18,
                        verbose_name="变动前余额",
                    ),
                ),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="此流水发生后的账户总余额",
                        max_digits=18,
                        verbose_name="变动后余额",
                    ),
                ),
                (
                    "available_balance_before",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=18,
                        verbose_name="变动前可用余额",
                    ),
                ),
                (
                    "available_balance_after",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=18,
                        verbose_name="变动后可用余额",
                    ),
                ),
                (
                    "frozen_balance_before",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=18,
                        verbose_name="变动前冻结余额",
                    ),
                ),
                (
                    "frozen_balance_after",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=18,
                        verbose_name="变动后冻结余额",
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="流水备注"),
                ),
                (
                    "account",
                    models.ForeignKey(
                        help_text="资金变动发生在哪一个账户",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.account",
                        verbose_name="关联账户",
                    ),
                ),
                (
                    "related_order",
                    models.ForeignKey(
                        blank=True,
                        help_text="与此流水相关的支付订单（若有）",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="settlements.paymentorder",
                        verbose_name="关联支付订单",
                    ),
                ),
            ],
            options={
                "verbose_name": "账户资金流水",
                "verbose_name_plural": "账户资金流水",
                "db_table_comment": "记录账户余额变动的详细流水",
            },
        ),
        migrations.CreateModel(
            name="RechargeInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="主键，BIGINT UNSIGNED AUTO_INCREMENT",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="记录创建时间，自动添加",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="记录更新时间，自动更新",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="发票金额"
                    ),
                ),
                (
                    "invoice_type",
                    models.SmallIntegerField(
                        choices=[(1, "电子普票"), (2, "纸质专票"), (3, "电子专票")],
                        default=1,
                        help_text="1-电子普票, 2-纸质专票, 3-电子专票",
                        verbose_name="发票类型",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="发票抬头")),
                (
                    "tax_number",
                    models.CharField(
                        blank=True,
                        help_text="企业发票需要提供税号",
                        max_length=50,
                        null=True,
                        verbose_name="税号",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[
                            (0, "申请中"),
                            (1, "已开具"),
                            (2, "已邮寄/发送"),
                            (3, "申请驳回"),
                        ],
                        default=0,
                        help_text="0-申请中, 1-已开具, 2-已邮寄/发送, 3-申请驳回",
                        verbose_name="开票状态",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="发票号码"
                    ),
                ),
                (
                    "invoice_code",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="发票代码"
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        help_text="哪个商户申请的发票",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.merchant",
                        verbose_name="申请商户",
                    ),
                ),
                (
                    "transaction_ledger",
                    models.ForeignKey(
                        help_text="关联到具体的充值交易流水",
                        limit_choices_to={"transaction_type": 1},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.transactionledger",
                        verbose_name="关联充值流水",
                    ),
                ),
            ],
            options={
                "verbose_name": "充值发票",
                "verbose_name_plural": "充值发票",
                "db_table_comment": "商户充值后申请发票的记录表",
            },
        ),
        migrations.CreateModel(
            name="Withdrawal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="主键，BIGINT UNSIGNED AUTO_INCREMENT",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="记录创建时间，自动添加",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="记录更新时间，自动更新",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="提现金额"
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[
                            (0, "申请中"),
                            (1, "处理中"),
                            (2, "成功"),
                            (3, "失败"),
                            (4, "已取消"),
                            (5, "审核拒绝"),
                        ],
                        default=0,
                        help_text="0-申请中, 1-处理中, 2-成功, 3-失败, 4-已取消, 5-审核拒绝",
                        verbose_name="提现状态",
                    ),
                ),
                (
                    "target_account_name",
                    models.CharField(
                        help_text="收款方银行账户名称（应加密）",
                        max_length=255,
                        verbose_name="提现至账户名",
                    ),
                ),
                (
                    "target_account_number",
                    models.CharField(
                        help_text="收款方银行账号（应加密）",
                        max_length=100,
                        verbose_name="提现至账号",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="银行名称"
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="提现成功或最终失败的时间",
                        null=True,
                        verbose_name="完成时间",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        help_text="从哪个商户账户提现",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.account",
                        verbose_name="提现账户",
                    ),
                ),
            ],
            options={
                "verbose_name": "提现记录",
                "verbose_name_plural": "提现记录",
                "db_table_comment": "商户提现申请记录表",
            },
        ),
        migrations.AddField(
            model_name="transactionledger",
            name="related_withdrawal",
            field=models.ForeignKey(
                blank=True,
                help_text="与此流水相关的提现记录（若有）",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.withdrawal",
                verbose_name="关联提现",
            ),
        ),
    ]
