# Generated by Django 5.2.1 on 2025-06-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionledger",
            name="transaction_type",
            field=models.SmallIntegerField(
                choices=[
                    (1, "充值"),
                    (2, "提现"),
                    (3, "支付"),
                    (4, "退款"),
                    (5, "服务费收取"),
                    (6, "服务费退回"),
                    (7, "账户冻结"),
                    (8, "账户解冻"),
                    (9, "系统调账增"),
                    (10, "系统调账减"),
                    (11, "支付失败解冻"),
                    (12, "提现失败解冻"),
                ],
                help_text="说明资金变动的业务性质",
                verbose_name="流水类型",
            ),
        ),
    ]
