"""
Django settings for settlement_system project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')

# Encryption Key for custom EncryptedField
FIELD_ENCRYPTION_KEY = os.getenv('FIELD_ENCRYPTION_KEY')
if not FIELD_ENCRYPTION_KEY:
    print("WARNING: FIELD_ENCRYPTION_KEY is not set in the environment. Generating a temporary key. THIS IS NOT SUITABLE FOR PRODUCTION.")
    from cryptography.fernet import Fernet
    FIELD_ENCRYPTION_KEY = Fernet.generate_key().decode()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-2n(^1t$7zrszc!28*9)s&hjtzqtyr7p^ftef-ud8z1r8)8d%%u')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() in ('true', '1', 't')

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_celery_beat',
    'django_celery_results',
    'django_filters',
    'drf_yasg',
    'core',
    'users',
    'organizations',
    'payment_channels',
    'accounts',
    'configurations',
    'settlement_preparation',
    'settlements',
    'tasks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'settlement_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'settlement_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME', 'settlement_db'),
        'USER': os.getenv('DB_USER', 'user'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'password'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '3306'),
    }
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{os.getenv('REDIS_HOST', 'redis')}:{os.getenv('REDIS_PORT', '6379')}/{os.getenv('REDIS_DB_DEFAULT', '1')}",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "PREFIX": "wzy",
        }
    }
}

CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'amqp://guest:guest@rabbitmq:5672//')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://redis:6379/2')
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly', # Changed to IsAuthenticatedOrReadOnly for more flexibility initially
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60), # Default is 5 minutes
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),    # Default is 1 day
    'ROTATE_REFRESH_TOKENS': False, # If True, each refresh request returns a new refresh token
    'BLACKLIST_AFTER_ROTATION': True, # Requires `django-rest-framework-simplejwt-blacklist` if True
    'UPDATE_LAST_LOGIN': True, # If True, last_login field of user is updated upon login

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY, # Uses Django's SECRET_KEY by default, ensure it's strong
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',), # Default is ('Bearer',)
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION', # Default
    'USER_ID_FIELD': 'id', # User model field for user_id claim
    'USER_ID_CLAIM': 'user_id', # JWT claim for user ID

    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5), # Not used if not using sliding tokens
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1), # Not used if not using sliding tokens

    # Custom Token Serializer (if you created one like CustomTokenObtainPairSerializer)
    # 'TOKEN_OBTAIN_SERIALIZER': 'users.serializers.CustomTokenObtainPairSerializer',
    # No, this is for the view, not the token itself. The view is already customized.
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Logging Configuration
# Ensure BASE_DIR is defined (it should be at the top of the file)
LOGGING_DIR = BASE_DIR / 'logs'
if not LOGGING_DIR.exists():
    LOGGING_DIR.mkdir(parents=True, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'django.server': {
            '()': 'django.utils.log.ServerFormatter',
            'format': '[{server_time}] {message}',
            'style': '{',
        }
    },
    'handlers': {
        'console': {
            'level': 'DEBUG', # Set to INFO in production
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file_app': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGGING_DIR / 'application.log',
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'file_django': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGGING_DIR / 'django.log',
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'django.server': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'django.server',
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'formatter': 'simple',
            # Add 'email_backend': 'django.core.mail.backends.filebased.EmailBackend' for testing if needed
            # and set 'EMAIL_FILE_PATH': LOGGING_DIR / 'error_emails'
        }
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file_django'],
            'level': 'INFO', # Django's own logs
            'propagate': True,
        },
        'django.server': {
            'handlers': ['django.server', 'file_django'], # Log server requests to console and file
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['mail_admins', 'file_django'], # Log request exceptions to mail and file
            'level': 'ERROR',
            'propagate': False,
        },
        # Example for a specific app - 'core' or your project's apps
        'core': {
            'handlers': ['console', 'file_app'],
            'level': 'DEBUG', # Or 'INFO' in production
            'propagate': False, # Prevent duplicate logging to parent 'django' logger
        },
        'users': {
            'handlers': ['console', 'file_app'],
            'level': 'DEBUG',
            'propagate': False,
        },
        # Add other apps here as needed
        'organizations': {
            'handlers': ['console', 'file_app'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'payment_channels': {
            'handlers': ['console', 'file_app'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'accounts': {
            'handlers': ['console', 'file_app'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'settlements': {
            'handlers': ['console', 'file_app'],
            'level': 'DEBUG',
            'propagate': False,
        },
         'configurations': {
            'handlers': ['console', 'file_app'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'tasks': {
            'handlers': ['console', 'file_app'],
            'level': 'DEBUG',
            'propagate': False,
        }
        # Default for other custom app loggers if not specified
        # '': { # Root logger configuration (optional)
        #     'handlers': ['console', 'file_app'],
        #     'level': 'INFO',
        #     'propagate': True,
        # },
    },
}

# Celery logging - if you want to customize it
# CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'amqp://guest:guest@rabbitmq:5672//')
# CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://redis:6379/2')
# CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
# CELERY_WORKER_LOG_FORMAT = "[%(asctime)s: %(levelname)s/%(processName)s] %(message)s"
# CELERY_WORKER_TASK_LOG_FORMAT = "[%(asctime)s: %(levelname)s/%(processName)s] [%(task_name)s(%(task_id)s)] %(message)s"
# CELERY_REDIRECT_STDOUTS_LEVEL = "INFO"
# CELERY_LOG_LEVEL = "INFO"

# Ensure ADMINS and MANAGERS are set for mail_admins handler to work properly
# ADMINS = [('Admin Name', 'admin@example.com')] # Replace with actual admin emails
# MANAGERS = ADMINS
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' # Or console, filebased for testing
# EMAIL_HOST = os.getenv('EMAIL_HOST', 'localhost')
# EMAIL_PORT = int(os.getenv('EMAIL_PORT', 25))
# EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
# EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
# EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'False').lower() in ('true', '1', 't')
# SERVER_EMAIL = os.getenv('SERVER_EMAIL', 'django_errors@example.com') # From address for error emails

# Alipay ISV Configuration
ALIPAY_ISV_CONFIG = {
    "APP_ID": os.getenv("ALIPAY_ISV_APP_ID"),
    "APP_PRIVATE_KEY_STRING": os.getenv("ALIPAY_ISV_APP_PRIVATE_KEY"),
    "ALIPAY_PUBLIC_KEY_STRING": os.getenv("ALIPAY_ISV_ALIPAY_PUBLIC_KEY"),
    "SIGN_TYPE": "RSA2",  # Standard for new apps
    "DEBUG": DEBUG,  # Use Django's DEBUG setting for Alipay sandbox mode by default
    "NOTIFY_URL": os.getenv("ALIPAY_ISV_DEFAULT_NOTIFY_URL"), # General callback for payments
    "RETURN_URL": os.getenv("ALIPAY_ISV_DEFAULT_RETURN_URL"), # General return URL for frontend
    "OAUTH_CALLBACK_URL": os.getenv("ALIPAY_ISV_OAUTH_CALLBACK_URL"), # Specific for app authorization
}
