# Generated by Django 5.2.1 on 2025-06-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IpConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="主键，BIGINT UNSIGNED AUTO_INCREMENT",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="记录创建时间，自动添加",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="记录更新时间，自动更新",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(unique=True, verbose_name="IP地址"),
                ),
                (
                    "access_type",
                    models.SmallIntegerField(
                        choices=[(1, "允许"), (0, "禁止")],
                        default=1,
                        help_text="1-允许访问, 0-禁止访问",
                        verbose_name="访问类型",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="关于此IP配置的说明，例如所属系统或原因",
                        null=True,
                        verbose_name="描述",
                    ),
                ),
            ],
            options={
                "verbose_name": "IP地址配置",
                "verbose_name_plural": "IP地址配置",
                "db_table_comment": "系统IP访问控制配置表",
            },
        ),
        migrations.CreateModel(
            name="RiskControlConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="主键，BIGINT UNSIGNED AUTO_INCREMENT",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="记录创建时间，自动添加",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="记录更新时间，自动更新",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="例如：单日最大交易金额限制",
                        max_length=255,
                        unique=True,
                        verbose_name="风控规则名称",
                    ),
                ),
                (
                    "config_type",
                    models.SmallIntegerField(
                        choices=[
                            (1, "金额上限"),
                            (2, "收款人限制"),
                            (3, "频率限制"),
                            (4, "IP地址限制"),
                            (5, "地理位置限制"),
                            (6, "设备指纹限制"),
                            (7, "支付渠道风控"),
                            (99, "其他"),
                        ],
                        help_text="风控规则的具体类别",
                        verbose_name="配置类型",
                    ),
                ),
                (
                    "rules",
                    models.JSONField(
                        help_text='JSON格式存储规则的具体参数，例如：{"max_amount_per_day": 50000, "currency": "CNY"} 或 {"blocked_keywords": ["gambling", "fraud"]}',
                        verbose_name="规则详情",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="标记此风控规则是否当前生效",
                        verbose_name="是否激活",
                    ),
                ),
            ],
            options={
                "verbose_name": "风控配置",
                "verbose_name_plural": "风控配置",
                "db_table_comment": "系统风控规则配置表",
            },
        ),
        migrations.CreateModel(
            name="WhitelistConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="主键，BIGINT UNSIGNED AUTO_INCREMENT",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="记录创建时间，自动添加",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="记录更新时间，自动更新",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="例如：大额交易用户白名单",
                        max_length=255,
                        verbose_name="白名单名称",
                    ),
                ),
                (
                    "id_type",
                    models.SmallIntegerField(
                        choices=[
                            (1, "身份证"),
                            (2, "护照"),
                            (3, "银行卡号"),
                            (4, "手机号"),
                            (5, "IP地址"),
                            (99, "其他"),
                        ],
                        help_text="白名单中记录的标识类型",
                        verbose_name="名单项类型",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="具体的白名单号码或地址（建议加密存储敏感信息）",
                        max_length=255,
                        verbose_name="白名单值",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="关于此白名单项的说明",
                        null=True,
                        verbose_name="描述",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="标记此白名单项是否生效",
                        verbose_name="是否激活",
                    ),
                ),
            ],
            options={
                "verbose_name": "白名单配置",
                "verbose_name_plural": "白名单配置",
                "db_table_comment": "系统白名单配置表",
                "unique_together": {("id_type", "value")},
            },
        ),
    ]
