# Generated by Django 5.2.1 on 2025-06-07 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("payment_channels", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="主键，BIGINT UNSIGNED AUTO_INCREMENT",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="记录创建时间，自动添加",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="记录更新时间，自动更新",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(
                        help_text="系统生成的唯一批次号",
                        max_length=64,
                        unique=True,
                        verbose_name="批次号",
                    ),
                ),
                (
                    "total_orders",
                    models.IntegerField(default=0, verbose_name="订单总数"),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=18,
                        verbose_name="订单总金额",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[
                            (0, "未校验"),
                            (1, "校验中"),
                            (2, "校验不通过"),
                            (3, "待审核"),
                            (4, "审核通过"),
                            (5, "审核不通过"),
                            (6, "待处理"),
                            (7, "处理中"),
                            (8, "部分成功"),
                            (9, "全部成功"),
                            (10, "处理失败"),
                            (11, "已作废"),
                            (12, "已挂起"),
                        ],
                        default=0,
                        help_text="表示当前批次的处理阶段",
                        verbose_name="批次状态",
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
                (
                    "audit_history",
                    models.JSONField(
                        blank=True,
                        help_text='存储审核人、时间、意见等，例如 [{"auditor_id": 1, "timestamp": "2023-01-01T10:00:00Z", "outcome": "approved", "comment": "Looks good"}]',
                        null=True,
                        verbose_name="审核历史",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        help_text="此支付批次属于哪个商户",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.merchant",
                        verbose_name="所属商户",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        help_text="通过系统上传此批次的用户",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_batches",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上传经办人",
                    ),
                ),
            ],
            options={
                "verbose_name": "支付批次",
                "verbose_name_plural": "支付批次",
                "db_table_comment": "商户上传的支付批次主表",
            },
        ),
        migrations.CreateModel(
            name="SubPaymentBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="主键，BIGINT UNSIGNED AUTO_INCREMENT",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="记录创建时间，自动添加",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="记录更新时间，自动更新",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "sub_batch_number",
                    models.CharField(
                        help_text="按规则拆分后生成的唯一子批次号",
                        max_length=64,
                        unique=True,
                        verbose_name="子批次号",
                    ),
                ),
                (
                    "total_orders",
                    models.IntegerField(default=0, verbose_name="订单总数"),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=18,
                        verbose_name="订单总金额",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[
                            (0, "待支付"),
                            (1, "支付中"),
                            (2, "部分成功"),
                            (3, "全部成功"),
                            (4, "支付失败"),
                            (5, "已取消"),
                        ],
                        default=0,
                        help_text="表示当前子批次的处理阶段",
                        verbose_name="子批次支付状态",
                    ),
                ),
                (
                    "parent_batch",
                    models.ForeignKey(
                        help_text="关联的主支付批次",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_batches",
                        to="settlements.paymentbatch",
                        verbose_name="父批次",
                    ),
                ),
                (
                    "payment_channel",
                    models.ForeignKey(
                        help_text="此子批次将通过哪个支付渠道处理",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="payment_channels.paymentchannel",
                        verbose_name="支付渠道",
                    ),
                ),
            ],
            options={
                "verbose_name": "子支付批次",
                "verbose_name_plural": "子支付批次",
                "db_table_comment": "按支付渠道或限额拆分后的子批次表",
            },
        ),
        migrations.CreateModel(
            name="PaymentOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="主键，BIGINT UNSIGNED AUTO_INCREMENT",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="记录创建时间，自动添加",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="记录更新时间，自动更新",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        help_text="系统生成的唯一订单号",
                        max_length=64,
                        unique=True,
                        verbose_name="订单号",
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        help_text="应加密存储",
                        max_length=255,
                        verbose_name="收款人姓名",
                    ),
                ),
                (
                    "recipient_account",
                    models.CharField(
                        help_text="银行卡号、支付宝账号等，应加密存储",
                        max_length=100,
                        verbose_name="收款账号",
                    ),
                ),
                (
                    "recipient_bank_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="收款银行名称",
                    ),
                ),
                (
                    "recipient_bank_branch",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="收款银行支行",
                    ),
                ),
                (
                    "recipient_phone",
                    models.CharField(
                        blank=True,
                        help_text="应加密存储",
                        max_length=20,
                        null=True,
                        verbose_name="收款人手机号",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="支付金额"
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[
                            (0, "未校验"),
                            (1, "校验通过"),
                            (2, "校验失败"),
                            (3, "待支付"),
                            (4, "支付中"),
                            (5, "支付成功"),
                            (6, "支付失败"),
                            (7, "已取消"),
                            (8, "已挂起"),
                            (9, "部分退款"),
                            (10, "全部退款"),
                        ],
                        default=0,
                        help_text="表示当前订单的处理阶段",
                        verbose_name="订单状态",
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="记录支付失败或校验失败的原因",
                        null=True,
                        verbose_name="错误信息",
                    ),
                ),
                (
                    "frozen_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="因特定原因（如风控）被冻结的金额",
                        max_digits=12,
                        verbose_name="冻结金额",
                    ),
                ),
                (
                    "is_frozen",
                    models.BooleanField(
                        default=False,
                        help_text="标记此订单金额是否被冻结",
                        verbose_name="是否冻结",
                    ),
                ),
                (
                    "service_fee_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="服务费金额",
                    ),
                ),
                (
                    "service_fee_frozen",
                    models.BooleanField(default=False, verbose_name="服务费是否冻结"),
                ),
                (
                    "service_fee_status",
                    models.SmallIntegerField(
                        choices=[
                            (0, "未收取"),
                            (1, "已收取"),
                            (2, "已退回"),
                            (3, "收取失败"),
                        ],
                        default=0,
                        help_text="0-未收取, 1-已收取, 2-已退回, 3-收取失败",
                        verbose_name="服务费状态",
                    ),
                ),
                (
                    "payment_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="支付成功时间"
                    ),
                ),
                (
                    "channel_transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="支付渠道返回的交易流水号",
                        max_length=128,
                        null=True,
                        verbose_name="渠道交易号",
                    ),
                ),
                (
                    "applied_rule",
                    models.ForeignKey(
                        blank=True,
                        help_text="此订单在处理过程中触发并应用了哪个规则",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payment_channels.orderrule",
                        verbose_name="应用的订单规则",
                    ),
                ),
                (
                    "arrival_channel_used",
                    models.ForeignKey(
                        blank=True,
                        help_text="最终实际的到账方式",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payment_channels.arrivalchannel",
                        verbose_name="实际使用到账通道",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.merchant",
                        verbose_name="所属商户",
                    ),
                ),
                (
                    "payment_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="settlements.paymentbatch",
                        verbose_name="所属支付批次",
                    ),
                ),
                (
                    "payment_channel_used",
                    models.ForeignKey(
                        blank=True,
                        help_text="最终实际执行支付的渠道",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payment_channels.paymentchannel",
                        verbose_name="实际使用支付渠道",
                    ),
                ),
                (
                    "payment_subject",
                    models.ForeignKey(
                        help_text="实际出款的支付主体（如银行账户或第三方支付商户号）",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="payment_channels.paymentsubject",
                        verbose_name="支付主体",
                    ),
                ),
                (
                    "sub_payment_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="settlements.subpaymentbatch",
                        verbose_name="所属子支付批次",
                    ),
                ),
            ],
            options={
                "verbose_name": "支付订单",
                "verbose_name_plural": "支付订单",
                "db_table_comment": "支付订单详细信息表",
                "indexes": [
                    models.Index(
                        fields=["status", "payment_channel_used"],
                        name="settlements_status_3dbae4_idx",
                    ),
                    models.Index(
                        fields=["merchant", "created_at"],
                        name="settlements_merchan_c63866_idx",
                    ),
                ],
            },
        ),
    ]
