# Generated by Django 5.2.1 on 2025-06-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settlements", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentbatch",
            name="audit_history",
            field=models.JSONField(
                blank=True,
                help_text='例如: [{"auditor_id": 1, "timestamp": "YYYY-MM-DDTHH:MM:SSZ", "action": "approve_initial_audit", "remark": "OK"}]',
                null=True,
                verbose_name="审核历史",
            ),
        ),
        migrations.AlterField(
            model_name="paymentbatch",
            name="status",
            field=models.SmallIntegerField(
                choices=[
                    (0, "未校验"),
                    (1, "格式校验中"),
                    (2, "格式校验失败"),
                    (3, "格式校验成功"),
                    (4, "待初审"),
                    (5, "初审通过"),
                    (6, "初审拒绝"),
                    (7, "待复审"),
                    (8, "复审通过/待支付"),
                    (9, "复审拒绝"),
                    (10, "支付处理中"),
                    (11, "部分支付成功"),
                    (12, "全部支付成功"),
                    (13, "支付失败"),
                    (14, "已作废/取消"),
                    (15, "待业务校验"),
                    (16, "业务校验失败"),
                    (17, "业务校验成功"),
                ],
                default=0,
                help_text="表示当前批次的处理阶段",
                verbose_name="批次状态",
            ),
        ),
        migrations.AlterField(
            model_name="paymentorder",
            name="status",
            field=models.SmallIntegerField(
                choices=[
                    (0, "未校验"),
                    (1, "待格式校验"),
                    (2, "格式校验成功"),
                    (3, "格式校验失败"),
                    (4, "待银行要素校验"),
                    (5, "银行要素校验成功"),
                    (6, "银行要素校验失败"),
                    (7, "待风控校验"),
                    (8, "风控通过"),
                    (9, "风控拒绝"),
                    (10, "待董监高校验"),
                    (11, "董监高通过"),
                    (12, "董监高拒绝"),
                    (13, "待支付"),
                    (14, "支付中"),
                    (15, "支付成功"),
                    (16, "支付失败"),
                    (17, "支付状态未知"),
                    (18, "已取消"),
                    (19, "已冻结"),
                    (20, "退款中"),
                    (21, "已退款"),
                    (22, "部分退款"),
                ],
                default=0,
                help_text="表示当前订单的处理阶段",
                verbose_name="订单状态",
            ),
        ),
        migrations.AlterField(
            model_name="subpaymentbatch",
            name="status",
            field=models.SmallIntegerField(
                choices=[
                    (0, "待处理"),
                    (1, "处理中"),
                    (2, "部分成功"),
                    (3, "全部成功"),
                    (4, "失败"),
                    (5, "已取消"),
                ],
                default=0,
                help_text="表示当前子批次的处理阶段",
                verbose_name="子批次支付状态",
            ),
        ),
    ]
