# Generated by Django 5.2.1 on 2025-06-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settlements", "0002_alter_paymentbatch_audit_history_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentorder",
            name="retries_count",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="订单支付的重试次数", verbose_name="重试次数"
            ),
        ),
    ]
