# Generated by Django 5.2.1 on 2025-06-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settlements", "0003_paymentorder_retries_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentorder",
            name="service_fee_status",
            field=models.SmallIntegerField(
                choices=[
                    (0, "服务费未收取"),
                    (1, "服务费已收取"),
                    (2, "服务费已退回"),
                    (3, "服务费收取失败"),
                ],
                default=0,
                help_text="服务费的收取状态",
                verbose_name="服务费状态",
            ),
        ),
    ]
